## =========================================================================
## module_allele_specific_sorting -- shared utilities (sourced, not run)
##
## Statistics (all on the 20,807 DI25 rho05 units, 20 hybrid populations):
##
##   among-population concordance  conc_ij = cor_pops(F_i, F_j)
##       F = population x unit aquilonia-allele frequency (Fmat). Signed:
##       + = the two loci distinguish the same populations in the same ancestry
##       direction. conc_resid uses the same profiles after regressing out
##       leave-one-chromosome-out genome-wide ancestry (pp_residualize_ancestry.R).
##
##   among-population LD (Ohta-style, normalised)
##       G_i   = var_pops(F_i) / (Fbar_i (1 - Fbar_i))   (Nei-type F_ST, unweighted pops)
##       rST_ij = cov_pops(F_i, F_j) / sqrt(Fbar_i(1-Fbar_i) Fbar_j(1-Fbar_j))
##             = conc_ij * sqrt(G_i * G_j)
##       sqrt(G_i G_j) is the CEILING on among-population LD that two loci with
##       these marginal F_STs could produce if they partitioned the populations
##       identically (|conc| = 1). The ratio rST / sqrt(G_i G_j) is conc itself:
##       high F_ST produces high among-population LD only to the extent that
##       partitions are shared. This is the formal version of "high F_ST but
##       not high LD".
##
##   within-population LD  r_w_ij
##       correlation of oriented genotypes after centring each unit within each
##       population (pooled within-population correlation, sample-size
##       weighted). r_w_adj additionally regresses each unit on the individual's
##       leave-one-chromosome-out hybrid index (within-population centred), which
##       removes admixture LD generated by among-individual variation in overall
##       ancestry -- the residual is the locus-specific within-population
##       association (the classic signal of selection on unlinked conspecific
##       combinations, e.g. BDMIs).
##       Missing genotypes (2.7%) are set to 0 after centring (mean imputation);
##       this shrinks r_w slightly towards 0, identically for observed and
##       permuted data.
##
## Unit genotypes are the units' representative SNPs (best-SNP / representative,
## strictly observed calls), oriented so that dosage counts the F. aquilonia
## allele -- the same orientation as Fmat (asserted on load).
## =========================================================================
suppressMessages({ library(data.table); library(ggplot2) })

PP_DIR   <- "module_population_partitioning/data"
OUT_DATA <- "module_allele_specific_sorting/data"
OUT_FIG  <- "module_allele_specific_sorting/Figures"
dir.create(OUT_DATA, showWarnings = FALSE, recursive = TRUE)
dir.create(OUT_FIG,  showWarnings = FALSE, recursive = TRUE)

N_UNITS <- 20807L
FIX_TH  <- 0.15     # phi = 0.85: population near-fixed if F >= 0.85 (aqu) or F <= 0.15 (pol)

## distance bins (bp), same breaks as module_population_partitioning
BP_BREAKS <- c(0, 5e3, 2e4, 1e5, 5e5, 2e6, 1e7, Inf)
BP_LABELS <- c("0-5kb", "5-20kb", "20-100kb", "100-500kb", "0.5-2Mb", "2-10Mb", ">10Mb")
CM_BREAKS <- c(0, 0.001, 0.01, 0.05, 0.2, 1, 5, Inf)
CM_LABELS <- c("<0.001", "0.001-0.01", "0.01-0.05", "0.05-0.2", "0.2-1", "1-5", ">5 cM")

theme_set(theme_bw(base_size = 10) +
          theme(strip.background = element_blank(), panel.grid.minor = element_blank()))

## ---------------------------------------------------------------------------
## units: Fmat + residuals + recombination, with provenance guards
## ---------------------------------------------------------------------------
load_units <- function() {
  obj <- readRDS(file.path(PP_DIR, "pp_units_Fmat.rds"))
  ra  <- readRDS(file.path(PP_DIR, "pp_residual_ancestry.rds"))
  u <- copy(obj$u); setDT(u); Fmat <- obj$Fmat; Resid <- ra$Resid
  stopifnot("expected the 20,807 DI25 rho05 units" = nrow(u) == N_UNITS,
            "Fmat columns must match u$group_id in order" = identical(colnames(Fmat), u$group_id),
            "Resid columns must match u$group_id in order" = identical(colnames(Resid), u$group_id),
            "Resid rows must match Fmat rows" = identical(rownames(Resid), rownames(Fmat)))

  ## genetic position + local recombination rate (pp_recombination.R convention)
  gm <- fread("data/Frufa_DTOL_PR.ref_genome.recmap")
  gm[, Chr := paste0("Chr", sub("chromosome_", "", chr))]
  setnames(gm, "cM/Mb", "cMMb")
  u[, cM_pos := NA_real_][, recomb_rate := NA_real_]
  for (ch in unique(u$Chr)) {
    gmc <- gm[Chr == ch]; setorder(gmc, pos)
    idx <- which(u$Chr == ch)
    u$cM_pos[idx]      <- approxfun(gmc$pos, gmc$cM,   rule = 2)(u$Pos[idx])
    u$recomb_rate[idx] <- approxfun(gmc$pos, gmc$cMMb, rule = 2)(u$Pos[idx])
  }
  ## units outside the map's physical range get rule=2 end values; flag them
  ## (pp_recombination.R found exactly 2: F11207 Chr21, F13909 Chr27)
  rng <- gm[, .(lo = min(pos), hi = max(pos)), by = Chr]
  u[rng, on = "Chr", off_map := Pos < i.lo | Pos > i.hi]
  u[off_map == TRUE, `:=`(cM_pos = NA_real_, recomb_rate = NA_real_)]

  ## Nei-type among-population F (unweighted populations), for the rST ceiling
  Fbar <- colMeans(Fmat, na.rm = TRUE)
  Fvar <- apply(Fmat, 2, function(x) mean((x - mean(x, na.rm = TRUE))^2, na.rm = TRUE))
  u[, G_nei := ifelse(Fbar > 0 & Fbar < 1, Fvar / (Fbar * (1 - Fbar)), NA_real_)]
  u[, Fbar := Fbar]
  u[, sorted := sort_class %in% c("aquilonia", "polyctena")]
  u[, idx := .I]
  list(u = u, Fmat = Fmat, Resid = Resid, H_loco = ra$H_loco, hybrid_pops = obj$hybrid_pops)
}

## ---------------------------------------------------------------------------
## individual genotypes, oriented to the aquilonia allele (mirrors pp_prep_units.R)
## ---------------------------------------------------------------------------
load_oriented_genotypes <- function(U) {
  u <- U$u
  inp <- readRDS("module_di25/data/di25_inputs.rds")
  e2  <- new.env(); load("data/hybrids_and_parents_maf005.Rdata", envir = e2)
  sd  <- e2$sample_data_with_parents
  G_all <- rbind(inp$GTs_hyb, inp$GTs_par)
  G_all <- G_all[rownames(G_all) %in% sd$Sample_ID, u$unit_marker, drop = FALSE]
  pops  <- sd$Population[match(rownames(G_all), sd$Sample_ID)]
  aq <- pops == "aquilonia_parent"; po <- pops == "polyctena_parent"
  sgn <- sign(colMeans(G_all[aq, , drop = FALSE], na.rm = TRUE) - colMeans(G_all[po, , drop = FALSE], na.rm = TRUE))
  hyb <- pops %in% U$hybrid_pops
  G <- G_all[hyb, , drop = FALSE]; pop <- pops[hyb]
  flip <- which(sgn < 0)
  if (length(flip)) G[, flip] <- 2L - G[, flip]
  G[, which(is.na(sgn) | sgn == 0)] <- NA
  colnames(G) <- u$group_id

  ## guard: population means of the oriented genotypes must reproduce Fmat
  Pm <- t(sapply(U$hybrid_pops, function(p) colMeans(G[pop == p, , drop = FALSE], na.rm = TRUE) / 2))
  d <- abs(Pm - U$Fmat[U$hybrid_pops, ]); d <- d[is.finite(d)]
  stopifnot("oriented genotypes do not reproduce Fmat" = max(d) < 1e-8)
  list(G = G, pop = pop)
}

## ---------------------------------------------------------------------------
## within-population standardised genotype matrices (columns have unit norm)
##   adj = FALSE: centred within population           -> r_w
##   adj = TRUE : also residualised on within-population-centred LOCO hybrid
##                index (one slope per unit, pooled within populations) -> r_w_adj
## ---------------------------------------------------------------------------
within_pop_Z <- function(GG, u, adj = FALSE) {
  G <- GG$G; pop <- GG$pop
  X <- G / 2
  for (p in unique(pop)) {
    r <- pop == p
    X[r, ] <- sweep(X[r, , drop = FALSE], 2, colMeans(X[r, , drop = FALSE], na.rm = TRUE))
  }
  if (adj) {
    chrs <- unique(u$Chr)
    obs <- !is.na(G)
    S_all <- rowSums(G / 2, na.rm = TRUE); N_all <- rowSums(obs)
    for (ch in chrs) {
      cols <- which(u$Chr == ch)
      h <- (S_all - rowSums(G[, cols, drop = FALSE] / 2, na.rm = TRUE)) / (N_all - rowSums(obs[, cols, drop = FALSE]))
      for (p in unique(pop)) { r <- pop == p; h[r] <- h[r] - mean(h[r]) }   # within-population centred
      Xc <- X[, cols, drop = FALSE]
      ok <- !is.na(Xc)
      Xc0 <- Xc; Xc0[!ok] <- 0
      b <- colSums(Xc0 * h) / colSums(ok * h^2)
      X[, cols] <- Xc - outer(h, b)
    }
  }
  X[is.na(X)] <- 0
  nrm <- sqrt(colSums(X^2)); nrm[nrm == 0] <- NA
  sweep(X, 2, nrm, "/")
}

## among-population standardised profile matrix (pops x units, unit norm columns)
among_pop_Z <- function(M) {
  M <- sweep(M, 2, colMeans(M, na.rm = TRUE))
  M[is.na(M)] <- 0
  nrm <- sqrt(colSums(M^2)); nrm[nrm == 0] <- NA
  sweep(M, 2, nrm, "/")
}

## ---------------------------------------------------------------------------
## chromosome-block bootstrap: B resamples of the chromosomes, returned as draw
## counts per chromosome (weights), in the order of `chrs`
## ---------------------------------------------------------------------------
chrom_draws <- function(chrs, B = 2000L, seed = 1L) {
  set.seed(seed)
  replicate(B, tabulate(match(sample(chrs, length(chrs), replace = TRUE), chrs), length(chrs)),
            simplify = FALSE)
}
