## =========================================================================
## module_population_partitioning -- follow-up 11: individual-influence and
## recent-backcross sensitivity. Does NOT modify any existing pp_*.R script
## or output, or R/10_geographic_prediction.R.
##
## Question: is the population-level pattern (concordance, the FST-vs-local-
## concordance relationship, sorting, the broad high-DI FST pattern) actually
## characteristic of whole populations, or generated by one or a few
## unusually influential individuals (e.g. recent backcrosses/migrants)
## within one or a few populations? Individual-level analogue of the
## leave-one-population-out checks already run throughout this module.
##
## *** DATASET NOTE (same as R/10_geographic_prediction.R) ***
## Uses the CURRENT primary dataset (module_di25_rho05, 20,807 units), not
## the legacy 11,052-unit lineage -- see that script's header / README.md
## "Migration to the rho05 primary dataset" for why.
##
## *** Sielva note *** Sielva is a genuine Alpine site (confirmed by the
## user, correcting this module's earlier mistaken "coordinate error" flag
## in R/10_geographic_prediction.R / FOLLOWUP_STATUS.md -- correction noted
## there). It is geographically disjunct from the 19 Fennoscandian
## populations. Run per the brief's own design (Sielva-exclusion is one of
## the required scenarios below) but reported explicitly as a distinct,
## disjunct-hybrid-zone case, not symmetric with dropping e.g. Karsikas.
##
## ---- efficient design (see chat discussion before this script existed) ----
## Individual-exclusion is CLOSED-FORM, not a per-individual refit: dropping
## individual i (oriented genotype g_i, unit-specific) from population p
## (n observed individuals at that unit) shifts the population mean by
##   f_p(-i) - f_p(all) = (f_p(all) - g_i) / (n - 1)
## computed once, vectorised, for all 165 individuals x ~20,800 units
## simultaneously (no loop, no refit). Downstream recomputation is done only
## for a SMALL, targeted set of exclusion scenarios (not all 165
## individuals): the single most influential individual overall; the most
## influential individual within EACH population (20 separate one-at-a-time
## scenarios, each touching only that population); the 5 most influential
## overall (one combined scenario); all of Sielva. Population-level LOO
## (already computed in pp_extra_robustness.R / R/10_geographic_prediction.R)
## is reused, not redone. Residualization against genome-wide ancestry is
## APPROXIMATED per scenario (recompute the leave-one-chromosome-out ancestry
## covariate H_loco fresh from the perturbed population means, but reuse the
## ORIGINAL per-unit alpha_u/beta_u regression coefficients rather than
## refitting 20,791 lm() calls per scenario) -- explicitly sanctioned by the
## brief ("recalculate or approximate"), and the concordance/FST recompute
## per scenario reuses the same fast per-chromosome-correlation-matrix
## pattern already proven in pp_extra_robustness.R (11.7s for 20 full
## population-LOO recomputations).
##
## Run from the formica_hybrid repo root, after pp_prep_units.R and
## pp_residualize_ancestry.R:
##   Rscript module_population_partitioning/R/11_individual_influence.R
## Writes: module_population_partitioning/data/followup/11_individual_influence.rds
##         module_population_partitioning/Figures/followup/11_*.png
## =========================================================================
suppressMessages(library(data.table))
t_start <- Sys.time()
OUTDIR <- "module_population_partitioning/data/followup"
FIGDIR <- "module_population_partitioning/Figures/followup"
dir.create(OUTDIR, showWarnings = FALSE, recursive = TRUE)
dir.create(FIGDIR, showWarnings = FALSE, recursive = TRUE)

## ---------------------------------------------------------------------
## 1. reconstruct individual-level oriented genotypes at each unit's
##    representative SNP (mirrors pp_prep_units.R's construction, but keeps
##    per-INDIVIDUAL values instead of collapsing straight to Fmat -- that
##    matrix was never saved, only the population-level aggregate was)
## ---------------------------------------------------------------------
devtools::load_all("~/gitlab/LDscnR/", quiet = TRUE)
obj <- readRDS("module_population_partitioning/data/pp_units_Fmat.rds")
rez <- readRDS("module_population_partitioning/data/pp_residual_ancestry.rds")
u <- copy(obj$u); Fmat <- obj$Fmat; setDT(u)
stopifnot(identical(colnames(Fmat), u$group_id))

inp <- readRDS("module_di25/data/di25_inputs.rds")
e2 <- new.env(); load("data/hybrids_and_parents_maf005.Rdata", envir = e2)
sd <- e2$sample_data_with_parents
GTs_all <- rbind(inp$GTs_hyb, inp$GTs_par)
GTs_all <- GTs_all[rownames(GTs_all) %in% sd$Sample_ID, ]
pops_all <- sd$Population[match(rownames(GTs_all), sd$Sample_ID)]
aqu_pops <- "aquilonia_parent"; pol_pops <- "polyctena_parent"
hybrid_pops <- setdiff(unique(pops_all), c(aqu_pops, pol_pops))
parent_rows <- grepl("_parent$", pops_all)

E <- GTs_all[, u$unit_marker, drop = FALSE]; colnames(E) <- u$group_id   # all 195 indiv x 20,807 units, RAW dosage 0/1/2
prep <- ohta_fast_prepare(E, pops = pops_all)
P <- prep$pop_means / 2
f_aqu_par <- P[aqu_pops, ]; f_pol_par <- P[pol_pops, ]
sign_aqu <- sign(f_aqu_par - f_pol_par)
flip <- which(sign_aqu < 0); undef <- which(is.na(sign_aqu) | sign_aqu == 0)

hyb_rows <- !parent_rows
G <- E[hyb_rows, , drop = FALSE] / 2                    # hybrids x units, oriented-TO-BE dosage/2 in [0,1]
if (length(flip)) G[, flip] <- 1 - G[, flip]
if (length(undef)) G[, undef] <- NA_real_
pops_hyb <- pops_all[hyb_rows]
stopifnot(identical(colnames(G), u$group_id))

## sanity check: population means of G must reproduce Fmat (verifies the
## orientation reconstruction is exact, not just plausible)
chk_pop <- "Karsikas"
chk <- colMeans(G[pops_hyb == chk_pop, ], na.rm = TRUE)
max_diff <- max(abs(chk - Fmat[chk_pop, ]), na.rm = TRUE)
cat(sprintf("[infl] sanity check: max |recomputed pop mean - Fmat| for %s = %.2e (should be ~0)\n", chk_pop, max_diff))
stopifnot(max_diff < 1e-8)

## ---------------------------------------------------------------------
## 2. closed-form per-individual, per-unit influence shift, then a single
##    continuous influence scalar per individual (RMS shift across units)
## ---------------------------------------------------------------------
n_indiv <- nrow(G); n_unit <- ncol(G)
pop_n_obs <- sapply(split(seq_along(pops_hyb), pops_hyb), function(idx) colSums(!is.na(G[idx, , drop = FALSE])))
## pop_n_obs: n_unit x n_pop matrix of per-unit observed-individual counts
pop_of_row <- pops_hyb
Fmat_row <- Fmat[pop_of_row, ]                            # n_indiv x n_unit, each row = that individual's OWN population mean
n_row <- t(pop_n_obs)[pop_of_row, ]                        # n_indiv x n_unit, per-unit n for that individual's population
shift <- (Fmat_row - G) / pmax(n_row - 1, 1)               # closed-form; NA where G is NA (individual didn't contribute anyway)
shift[n_row <= 1] <- NA_real_                               # undefined for singleton populations at that unit

influence_rms <- sqrt(rowMeans(shift^2, na.rm = TRUE))
influence_mad <- rowMeans(abs(shift), na.rm = TRUE)
het <- rowMeans(E[hyb_rows, , drop = FALSE] == 1, na.rm = TRUE)   # heterozygosity: orientation-invariant, raw dosage
miss <- rowMeans(is.na(E[hyb_rows, , drop = FALSE]))
ancestry <- rowMeans(G, na.rm = TRUE)                        # individual-level genome-wide (DI25-panel) hybrid index

indiv_tab <- data.table(Sample_ID = rownames(G), Population = pops_hyb, n_pop = as.integer(table(pops_hyb)[pops_hyb]),
                        influence_rms = influence_rms, influence_mad = influence_mad,
                        genome_wide_ancestry = ancestry, heterozygosity = het, missingness = miss)
setorder(indiv_tab, -influence_rms)
cat(sprintf("\n[infl] %d hybrid individuals scored; influence_rms range [%.5f, %.5f], median %.5f\n",
            nrow(indiv_tab), min(indiv_tab$influence_rms), max(indiv_tab$influence_rms), median(indiv_tab$influence_rms)))
cat("[infl] top 10 most influential individuals:\n"); print(indiv_tab[1:10])

top1_overall <- indiv_tab[1, Sample_ID]
top5_overall <- indiv_tab[1:5, Sample_ID]
top1_per_pop <- indiv_tab[, .SD[which.max(influence_rms)], by = Population][, .(Population, Sample_ID, influence_rms)]
sielva_ids <- indiv_tab[Population == "Sielva", Sample_ID]
cat(sprintf("\n[infl] most influential overall: %s (rms=%.5f)\n", top1_overall, indiv_tab[1, influence_rms]))
cat("[infl] most influential individual per population:\n"); print(top1_per_pop)

## ---------------------------------------------------------------------
## 3. targeted exclusion scenarios: rebuild the population x unit matrix,
##    genome-wide ancestry covariate, and approximate residuals with the
##    flagged individual(s) removed; recompute the headline statistics.
## ---------------------------------------------------------------------
wc_ac <- function(Gm, pop) {   # identical estimator to pp_prep_units.R / di25_fst_vs_di.R
  levs <- unique(pop); M <- ncol(Gm)
  N <- P2 <- H <- matrix(0, length(levs), M)
  for (k in seq_along(levs)) {
    gk <- Gm[pop == levs[k], , drop = FALSE]
    n <- colSums(!is.na(gk)); s <- colSums(gk, na.rm = TRUE); het2 <- colSums(gk == 1, na.rm = TRUE)
    N[k, ] <- n; P2[k, ] <- ifelse(n > 0, s / (2 * n), 0); H[k, ] <- ifelse(n > 0, het2 / n, 0)
  }
  C <- colSums(N); sumN2 <- colSums(N^2); r <- colSums(N > 0)
  nbar <- C / r; nc <- (C - sumN2 / C) / (r - 1)
  pbar <- colSums(N * P2) / C; hbar <- colSums(N * H) / C
  s2 <- colSums(N * sweep(P2, 2, pbar)^2) / ((r - 1) * nbar)
  msp <- pbar * (1 - pbar)
  a <- (nbar / nc) * (s2 - (1 / (nbar - 1)) * (msp - ((r - 1) / r) * s2 - 0.25 * hbar))
  b <- (nbar / (nbar - 1)) * (msp - ((r - 1) / r) * s2 - ((2 * nbar - 1) / (4 * nbar)) * hbar)
  cc <- 0.5 * hbar
  list(a = a, abc = a + b + cc)
}
recompute_near <- function(Fm, u) {   ## identical pattern to pp_extra_robustness.R
  chrs <- unique(u$Chr)
  near_r <- near_absr <- rep(NA_real_, nrow(u))
  for (ch in chrs) {
    idx <- which(u$Chr == ch); if (length(idx) < 2) next
    sub <- Fm[, idx, drop = FALSE]; pos <- u$Pos[idx]
    Rm <- suppressWarnings(cor(sub, use = "pairwise.complete.obs"))
    for (k in seq_along(idx)) {
      d <- abs(pos - pos[k]); near <- which(d > 0 & d <= 1e5)
      if (!length(near)) next
      rs <- Rm[k, near]
      near_r[idx[k]] <- mean(rs, na.rm = TRUE); near_absr[idx[k]] <- mean(abs(rs), na.rm = TRUE)
    }
  }
  list(near_r = near_r, near_absr = near_absr)
}
chrs_all <- unique(u$Chr)
H_loco_from_Fmat <- function(Fm) {   ## same construction as pp_residualize_ancestry.R step 1
  S_p <- rowSums(Fm, na.rm = TRUE); N_p <- rowSums(!is.na(Fm))
  Hl <- matrix(NA_real_, nrow(Fm), length(chrs_all), dimnames = list(rownames(Fm), chrs_all))
  for (ch in chrs_all) {
    idx <- which(u$Chr == ch); sub <- Fm[, idx, drop = FALSE]
    sum_c <- rowSums(sub, na.rm = TRUE); n_c <- rowSums(!is.na(sub))
    Hl[, ch] <- (S_p - sum_c) / (N_p - n_c)
  }
  Hl
}
fit_geo_r2 <- function(Y, lat, lon) {   ## reused from R/10_geographic_prediction.R
  X <- cbind(1, lat - mean(lat), lon - mean(lon))
  B <- solve(crossprod(X), crossprod(X, Y))
  Yhat <- X %*% B
  1 - sum((Y - Yhat)^2) / sum(scale(Y, center = TRUE, scale = FALSE)^2)
}
bc <- fread("data/bioclimatic_variables.csv")
bc[Location == "Nyrhispera1", Location := "Nyrhispera74"]; bc[Location == "Nyrhispera2", Location := "Nyrhispera75"]

run_scenario <- function(drop_ids, label) {
  keep <- !(rownames(G) %in% drop_ids)
  stopifnot(sum(keep) >= 2)
  Fm_partial <- t(sapply(split(seq_len(nrow(G))[keep], pops_hyb[keep]), function(idx) colMeans(G[idx, , drop = FALSE], na.rm = TRUE)))
  ## a scenario CAN empty a whole population (e.g. "top5 overall" happens to
  ## include all 3 Svanvik1 individuals, n=3 being the smallest population --
  ## itself a finding: influence_rms is only partially normalized for n, small
  ## populations still surface disproportionately in "most influential" lists).
  ## Reindex to the full 20-population frame with NA rows for any population
  ## fully dropped, rather than erroring.
  Fm_new <- matrix(NA_real_, nrow(Fmat), ncol(Fmat), dimnames = dimnames(Fmat))
  Fm_new[rownames(Fm_partial), ] <- Fm_partial
  Fm_new[is.nan(Fm_new)] <- NA_real_
  ac <- wc_ac(E[hyb_rows, , drop = FALSE][keep, , drop = FALSE], pops_hyb[keep])
  FST_new <- ifelse(ac$abc > 0, ac$a / ac$abc, NA_real_)
  near <- recompute_near(Fm_new, u)
  rho_absr <- cor(FST_new, near$near_absr, use = "pairwise.complete.obs", method = "spearman")
  rho_r <- cor(FST_new, near$near_r, use = "pairwise.complete.obs", method = "spearman")
  ## approximate residualization: fresh H_loco from the perturbed Fmat, ORIGINAL alpha_u/beta_u kept fixed
  Hl_new <- H_loco_from_Fmat(Fm_new)
  chr_of_unit <- u$Chr
  pred <- matrix(NA_real_, nrow(Fm_new), ncol(Fm_new), dimnames = dimnames(Fm_new))
  for (ch in chrs_all) {
    idx <- which(chr_of_unit == ch)
    pred[, idx] <- outer(Hl_new[, ch], rez$beta_u[idx]) + matrix(rez$alpha_u[idx], nrow(Fm_new), length(idx), byrow = TRUE)
  }
  Resid_new <- Fm_new - pred
  pop_present <- rowSums(!is.na(Fm_new)) > 0    ## a scenario can fully empty a population (see note above)
  Resid_present <- Resid_new[pop_present, , drop = FALSE]
  pca_ve1 <- tryCatch({
    keep_u <- apply(Resid_present, 2, function(x) all(is.finite(x)) && sd(x) > 0)
    pc <- prcomp(Resid_present[, keep_u, drop = FALSE], center = TRUE, scale. = FALSE)
    100 * pc$sdev[1]^2 / sum(pc$sdev^2)
  }, error = function(e) NA_real_)
  geo <- bc[match(rownames(Resid_present), Location), .(Latitude, Longitude)]
  geoR2 <- tryCatch({
    keep_u <- apply(Resid_present, 2, function(x) all(is.finite(x)) && sd(x) > 0)
    Ystd <- scale(Resid_present[, keep_u, drop = FALSE], center = TRUE, scale = TRUE)
    fit_geo_r2(Ystd, geo$Latitude, geo$Longitude)
  }, error = function(e) NA_real_)
  data.table(scenario = label, n_dropped = length(drop_ids), n_remaining = sum(keep),
            median_FST = median(FST_new, na.rm = TRUE), rho_FST_vs_absr = rho_absr, rho_FST_vs_r = rho_r,
            residual_PC1_pct = pca_ve1, geoR2 = geoR2)
}

baseline <- run_scenario(character(0), "baseline (none dropped)")
sc_top1 <- run_scenario(top1_overall, sprintf("drop top1 overall (%s)", top1_overall))
sc_top5 <- run_scenario(top5_overall, "drop top5 overall")
sc_sielva <- run_scenario(sielva_ids, "drop all Sielva")
sc_top1_per_pop <- rbindlist(lapply(seq_len(nrow(top1_per_pop)), function(k) {
  run_scenario(top1_per_pop$Sample_ID[k], sprintf("drop top1 in %s (%s)", top1_per_pop$Population[k], top1_per_pop$Sample_ID[k]))
}))
scenarios <- rbind(baseline, sc_top1, sc_top5, sc_sielva, sc_top1_per_pop)
cat("\n[infl] scenario comparison (baseline vs targeted exclusions):\n")
print(scenarios[, .(scenario, n_dropped, median_FST = round(median_FST, 4), rho_FST_vs_absr = round(rho_FST_vs_absr, 4),
                    rho_FST_vs_r = round(rho_FST_vs_r, 4), residual_PC1_pct = round(residual_PC1_pct, 2), geoR2 = round(geoR2, 4))])

## reuse (not redo) the existing population-level LOO already computed
extra <- readRDS("module_population_partitioning/data/pp_extra_robustness.rds")
cat(sprintf("\n[infl] (reused, not recomputed) existing population-level LOO range for FST-vs-|r|: [%.3f, %.3f] (full sample: %.3f)\n",
            min(extra$loo$rho_absr), max(extra$loo$rho_absr), extra$full_rho$rho_absr))

## ---------------------------------------------------------------------
## 4. figures
## ---------------------------------------------------------------------
suppressMessages(library(ggplot2))
theme_ms <- theme_bw(base_size = 12) + theme(strip.background = element_blank(), panel.grid.minor = element_blank())
indiv_tab[, Population := factor(Population, levels = indiv_tab[, median(influence_rms), by = Population][order(V1), Population])]

fig_by_pop <- ggplot(indiv_tab, aes(Population, influence_rms)) +
  geom_boxplot(outlier.shape = NA, fill = "grey90") +
  geom_jitter(aes(colour = Population == "Sielva"), width = 0.15, size = 1.8) +
  scale_colour_manual(values = c(`TRUE` = "firebrick", `FALSE` = "grey30"), guide = "none") +
  labs(x = NULL, y = "individual influence (RMS profile shift)", title = "Individual influence by population (red = Sielva)") +
  theme_ms + theme(axis.text.x = element_text(angle = 60, hjust = 1))
ggsave(file.path(FIGDIR, "11_influence_by_population.png"), fig_by_pop, width = 10, height = 5.5, dpi = 200)

fig_covar <- ggplot(indiv_tab, aes(genome_wide_ancestry, influence_rms, colour = heterozygosity)) +
  geom_point(size = 2.3) + scale_colour_viridis_c() +
  labs(x = "individual genome-wide (DI25-panel) ancestry", y = "influence (RMS)", colour = "heterozygosity",
      title = "Influence vs individual ancestry and heterozygosity") +
  theme_ms
ggsave(file.path(FIGDIR, "11_influence_vs_ancestry_het.png"), fig_covar, width = 7.5, height = 5.5, dpi = 200)

sc_long <- melt(scenarios[scenario %in% c("baseline (none dropped)", sprintf("drop top1 overall (%s)", top1_overall),
                                          "drop top5 overall", "drop all Sielva")],
                id.vars = "scenario", measure.vars = c("rho_FST_vs_absr", "rho_FST_vs_r", "residual_PC1_pct", "geoR2"))
sc_long[, scenario := factor(scenario, levels = c("baseline (none dropped)", sprintf("drop top1 overall (%s)", top1_overall),
                                                  "drop top5 overall", "drop all Sielva"))]
fig_before_after <- ggplot(sc_long, aes(scenario, value, fill = scenario)) +
  geom_col() + facet_wrap(~variable, scales = "free_y") +
  labs(x = NULL, y = NULL, title = "Principal statistics: baseline vs targeted individual/Sielva exclusion") +
  theme_ms + theme(axis.text.x = element_blank(), legend.position = "bottom", legend.title = element_blank())
ggsave(file.path(FIGDIR, "11_before_after.png"), fig_before_after, width = 9, height = 6.5, dpi = 200)
cat("\n[infl] figures saved: 11_influence_by_population.png, 11_influence_vs_ancestry_het.png, 11_before_after.png\n")

## ---------------------------------------------------------------------
## 5. verdict + save
## ---------------------------------------------------------------------
key_stat_drift <- max(abs(scenarios[-1, rho_FST_vs_absr] - baseline$rho_FST_vs_absr))
verdict <- if (key_stat_drift < 0.02) {
  "stable: no single individual or the top-5 combined materially changes the headline FST-vs-concordance statistic -- population-level, not individual-driven"
} else {
  "unstable: at least one targeted exclusion scenario shifts the headline statistic by >0.02 -- inspect which scenario and whether it points to Sielva or a specific population's own most-influential member"
}
cat(sprintf("\n[infl] VERDICT: %s (max |scenario - baseline| in rho_FST_vs_absr = %.4f)\n", verdict, key_stat_drift))

result <- list(indiv_tab = indiv_tab, top1_overall = top1_overall, top5_overall = top5_overall,
               top1_per_pop = top1_per_pop, sielva_ids = sielva_ids, scenarios = scenarios,
               existing_population_loo_reused = extra$loo, key_stat_drift = key_stat_drift, verdict = verdict,
               dataset_note = "uses the current rho05 (20,807-unit) dataset, approximate residualization (see script header)",
               session_info = sessionInfo(), run_time = Sys.time(), elapsed_secs = as.numeric(difftime(Sys.time(), t_start, units = "secs")))
saveRDS(result, file.path(OUTDIR, "11_individual_influence.rds"))
cat(sprintf("\n[infl] saved -> %s (elapsed %.1fs)\n", file.path(OUTDIR, "11_individual_influence.rds"), result$elapsed_secs))
